### ISSUE TITLE
Please disable auto selection and copy from code window

### ISSUE THREAD

**Issue by sanperrier** [tudou527/marketch#121]
It's really annoying.
I don't want to copy all the styles but single value or line;

**Comment by pkamb** [comment]
I love the auto-copy for grabbing the `Content` value. It would be even better if I could do something like double-click to copy directly from the image, rather than having to go to the sidebar.

But it's **extremely** annoying not being able to select and copy only the color value from the `Code` block. I'm constantly having to paste that block into a text editor, then individually select the color code.

You could also add an individual field for easy copy of Color, as is done with Font Size.

<img width="212" alt="screen shot 2016-11-17 at 1 45 20 pm" src="https://cloud.githubusercontent.com/assets/342355/20408885/48e2187e-accc-11e6-9e03-bf48dabda474.png">
