### ISSUE TITLE
Doesn't work with Sketch 3.5.1

### ISSUE THREAD

**Issue by Darwinium** [tudou527/marketch#75]
I've tried different ways but export doesn't work(

**Comment by giuseppebergman** [comment]
Hi,
Are you sure you have updated to version 1.0.13? It works here with Sketch 3.5.1 (except for the "-" already opened issue).

**Comment by Darwinium** [comment]
Yes, I updated plugin. Select one artboard, choose export only selected artboards and folder and nothing happens(

Before I deleted old version and install again

Look here http://screencast.com/t/bSvq1Idhcl

**Comment by giuseppebergman** [comment]
There's definitely a problem with your plugin version: the second checkbox of v1.0.13 dialog box should read "Save Sketch file", NOT "Reveal in Finder after exporting" as shown in your screencast.

Maybe an old version lies within a subfolder? "marketch" will show at the root of the "Plugins" menu whatever subfolder you place the plugin in, so that may be a source of confusion (has been for me).

**Comment by Darwinium** [comment]
Sketch Toolbox doesn't work. After deleting marketch manualy and installing from github it works!

Thank you.
